### ISSUE TITLE
Distinguish this repo with tidb-dev-guide

### ISSUE THREAD

**Issue by tisonkun** [pingcap/docs-appdev#34]
I can see that we use "App Development Guide" in index.

Maybe we can rename this repo as `app-dev-guide` so that contributors come to pingcap org won't be confuse by

* https://github.com/pingcap/dev-guide
* https://github.com/pingcap/tidb-dev-guide

cc @bb7133 @TomShawn

**Comment by sunxiaoguang** [comment]
> @TomShawn as "developer" in our community can be application developer or kernel developer (fact), I'd prefer use "appdev" as we already use it in some conversation. `developers` can work in term of distinguishing from `tidb-dev-guide`, but may cause confusion "what's developer?"

appdev +1
